apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: development
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.2
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - containerPort: 3000
        env:
        - name: GF_USERS_DEFAULT_THEME
          value: "light"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
          # volumeMounts:
          # - name: grafana-config
          #   mountPath: /etc/grafana/provisioning
# volumes:
#   - name: grafana-config
#     configMap:
#       name: grafana-config
