apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: development
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.49
        ports:
        - containerPort: 16686
        - containerPort: 4317
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
