# https://github.com/grafana/tempo/issues/2769

ingester:
  enabled: true
  replicas: 1
  config:
    max_block_duration: 30m    
    replication_factor: 1      

metricsGenerator:
  enabled: true
  replicas: 1
  config:
    storage:
      remote_write:
        - url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write
          send_exemplars: true

distributor:
  enabled: true
  replicas: 1

compactor:
  enabled: true
  replicas: 1
  config:
    compaction:
      block_retention: 168h # 7d
      compaction_window: 4h

querier:
  enabled: true
  replicas: 1

queryFrontend:
  query:
    enabled: false
  enabled: true
  replicas: 1

multitenancyEnabled: false

traces:
  otlp:
    http:
      enabled: true
      receiverConfig: {}
    grpc:
      enabled: true
      receiverConfig: {}

storage:
  trace:
    backend: s3                        
    s3:
      bucket: tempo           
      endpoint: ax70azibgchm.compat.objectstorage.eu-paris-1.oraclecloud.com
      access_key: a
      secret_key: b

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] 
      generate_native_histograms: both

memcached:
  enabled: true
  replicas: 1 

memcachedExporter:
  enabled: true

metaMonitoring:
  serviceMonitor:
    enabled: true
    labels: 
      release: prometheus

minio:
  enabled: false