apiVersion: v1
kind: Service
metadata:
  name: axum-demo
  namespace: development
  labels:
    app: axum-demo
spec:
  selector:
    app: axum-demo
  ports:
  - name: web
    port: 80
    targetPort: 8080

