apiVersion: v1
kind: Service
metadata:
  name: axum-demo
  namespace: dev
  labels:
    app: axum-demo
spec:
  selector:
    app: axum-demo
  ports:
  - name: web
    port: 80
    targetPort: 8080

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axum-demo
  namespace: dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: axum-demo
  namespaceSelector:
    matchNames:
    - dev
  endpoints:
  - port: web

