apiVersion: v1
kind: Service
metadata:
  name: axum-demo
  namespace: development
spec:
  selector:
    app: axum-demo
  ports:
  - name: axum-demo
    port: 80
    protocol: TCP
    targetPort: 8080

