apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: development
spec:
  selector:
    app: jaeger
  ports:
  - name: collector
    protocol: TCP
    port: 4317
  - name: query
    protocol: TCP
    port: 16686
