apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: dev
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: collector
    protocol: TCP
    port: 4317
  - name: admin
    protocol: TCP
    port: 14269
  - name: query
    protocol: TCP
    port: 16686

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
  namespace: dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: jaeger
  namespaceSelector:
    matchNames:
    - dev
  endpoints:
  - port: admin
