# Dynamically linked : Debian
FROM lukemathwalker/cargo-chef:latest-rust-1.83.0-alpine3.20 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# For swaggerui, add flag "reqwest" to "utoipa-swagger-ui" to avoid this 
RUN apk --no-cache add curl
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --recipe-path recipe.json
COPY . .
RUN cargo build --bin axum-demo

FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=builder /app/target/debug/axum-demo /usr/local/bin
ENTRYPOINT ["/usr/local/bin/axum-demo"]