FROM rust:1.85-slim-bookworm AS chef
RUN cargo install bacon
RUN cargo install cargo-chef 
RUN apt update && apt install -y pkg-config libssl-dev
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --bin axum-demo --recipe-path recipe.json

COPY . .
RUN cargo build --bin axum-demo 
ENTRYPOINT ["bacon", "run", "--", "--bin", "axum-demo"]

# for cli like : lscpu, readelf, ps, arp
# RUN apt install -y strace procps htop binutils net-tools