apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  namespace: development
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        kubernetes.io/hostname: "minikube"
      containers:
      - name: prometheus
        image: prom/prometheus:v2.47.0
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - containerPort: 9090
        command:
        - /bin/prometheus
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.enable-remote-write-receiver
        - --enable-feature=native-histograms
