apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: basic-daemonset
  namespace: development
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:
        timeout: 1s
      filter/allowlist:
        spans:
          include:
            match_type: strict
            services:
            - axum-otpl
      k8sattributes:
          extract:
            metadata:
              - k8s.pod.name
              - k8s.pod.uid
              - k8s.deployment.name
              - k8s.namespace.name
              - k8s.node.name
              - k8s.pod.start_time

    exporters:
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, filter/allowlist, k8sattributes]
          exporters: [otlp/jaeger]




