apiVersion: apps/v1
kind: Deployment
metadata:
  name: axum-demo
  namespace: development
  labels:
    app.kubernetes.io/name: axum-demo
    app.kubernetes.io/version: v1.0.3
    app.kubernetes.io/component: web-api
    app.kubernetes.io/environment: development
  annotations:
    imageregistry: "https://hub.docker.com"
    imagelink: "https://hub.docker.com/layers/aimeric/axum-demo/v1.0.3/images/sha256-6ca46403a8d2ff4eafb7cd9cf2b8c24d990b084137f41efef7ec1a2bd28a7400?context=repo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axum-demo
  template:
    metadata:
      labels:
        app: axum-demo
        # annotations:
        #   sidecar.opentelemetry.io/inject: "true"
    spec:
      nodeSelector:
        kubernetes.io/hostname: "minikube"
      containers:
      - name: axum-demo
        image: aimeric/axum-demo:v1.0.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 20
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: rust_log
        - name: SERVICE_DB_USER
          valueFrom:
            secretKeyRef:
              name: axum-demo
              key: service_db_user
        - name: SERVICE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: axum-demo
              key: service_db_password
        - name: SERVICE_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: service_db_host
        - name: SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: service_db_name
        - name: SERVICE_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: service_db_port
        - name: SERVICE_PWD_KEY
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: service_pwd_key
        - name: SERVICE_TOKEN_KEY
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: service_token_key
        - name: SERVICE_TOKEN_DURATION_SEC
          valueFrom:
            secretKeyRef:
              name: axum-demo
              key: service_token_duration_sec
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: app_host
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: app_port
        - name: APP_WEB_FOLDER
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: app_web_folder
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: otel_exporter_otlp_endpoint
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: otel_service_name
        - name: OTEL_SERVICE_VERSION
          valueFrom:
            configMapKeyRef:
              name: axum-demo
              key: otel_service_version

