# docker run  --privileged -it debian:bookworm /bin/bash
# apt update && apt install -y procps nftables iproute2 conntrack vim git htop lsof iputils-ping dnsutils systemd curl certbot
# (root, nginx)
# systemctl enable nftables.service


# ss -4ntlp
# nc -w1 -vzu 128.140.71.58 22
# nft (-N) list ruleset
# nft -f input.nft
# conntrack -L
# https://man.archlinux.org/man/nft.8


# L3 protocol : ip, ip6, inet, arp, bridge, netdev
# L4 protocol : icmp, esp, ah, comp, udp, udplite, tcp, dccp, sctp 
flush ruleset

table ip filter_table {
    set ssh_banned_ips {
        typeof ip saddr
        flags timeout
    }

    chain input_chain_main {
        type filter hook input priority 0; policy accept;

        ct state established,related counter accept
        ct state invalid counter drop
        iif lo counter accept

        ip protocol vmap {
            tcp: jump tcp_chain,
            udp: jump udp_chain,
            icmp: jump icmp_chain
        }

        counter drop
    }

    chain tcp_chain {
        tcp dport 22 jump ssh_chain
        counter accept
    }

    chain udp_chain {
        counter accept
    }

    chain icmp_chain {
        counter accept
    }

    chain ssh_chain {
        ct state new ip saddr @ssh_banned_ips drop
        ct state new limit rate over 2/minute burst 3 packets add @ssh_banned_ips { ip saddr timeout 1m }
    }
}
