apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: development
  name: compute-resources
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
