receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

  resourcedetection:
    detectors: [env, gcp]
    timeout: 2s
    override: false

  resource:
    attributes:
    - key: service.name
      value: ${env:K_SERVICE}
      action: upsert
    - key: service.instance.id
      from_attribute: faas.id
      action: insert

exporters:
  googlecloud:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, resource, memory_limiter, batch]
      exporters: [googlecloud]
