apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: hello-test
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: axum-demo
            port:
              number: 80
