apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axum-demo
  namespace: development
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: axum-demo
  namespaceSelector:
    matchNames:
    - development

  endpoints:
  - port: web
