apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  name: green-harvest-web-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/container-dependencies: '{"app":["collector"]}'
    spec:
      containers:
      - image: "%APP_IMAGE%"
        name: app
        ports:
        - containerPort: 8080
      - image: "%OTELCOL_IMAGE%"
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133
