# kubeControllerManager:
#   endpoints:
#     - 10.0.1.158
#     - 10.0.1.143
#     - 10.0.1.190
#   service:
#     port: 10257
#     targetPort: 10257
#   serviceMonitor:
#     https: true
#     insecureSkipVerify: true
# kubeScheduler:
#   endpoints:
#     - 10.0.1.158
#     - 10.0.1.143
#     - 10.0.1.190
#   service:
#     port: 10259
#     targetPort: 10259
#   serviceMonitor:
#     https: true
#     insecureSkipVerify: true
# kubeEtcd:
#   endpoints:
#     - 10.0.1.158
#     - 10.0.1.143
#     - 10.0.1.190
#   service:
#     port: 2381
#     targetPort: 2381
# kubeProxy:
#   service:
#     port: 10249
#     targetPort: 10249
#     selector:
#       k8s-app: cilium-kube-proxy
#   serviceMonitor:
#     proxyUrl: http://pushprox-kube-proxy-proxy.kube-system.svc:8080
#     https: false
#     relabelings:
#       - action: replace
#         sourceLabels:
#           - __meta_kubernetes_pod_ip
#         targetLabel: pod_ip
#       - action: replace
#         sourceLabels:
#           - __meta_kubernetes_pod_node_name
#         targetLabel: instance

