kubeControllerManager:
  endpoints:
    - 10.0.1.112
    - 10.0.1.28
    - 10.0.1.44
  service:
    port: 10257
    targetPort: 10257
kubeScheduler:
  endpoints:
    - 10.0.1.112
    - 10.0.1.28
    - 10.0.1.44
  service:
    port: 10259
    targetPort: 10259
kubeEtcd:
  endpoints:
    - 10.0.1.112
    - 10.0.1.28
    - 10.0.1.44
  service:
    port: 2381
    targetPort: 2381
kubeProxy:
  endpoints:
    - 10.0.1.112
    - 10.0.1.28
    - 10.0.1.44
  service:
    port: 10249
    targetPort: 10249

alertmanager:
  alertmanagerSpec:
    storage: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: oci-bv
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 50Gi

# https://github.com/prometheus-community/helm-charts/issues/5080
# https://github.com/prometheus-community/helm-charts/issues/2703
# https://github.com/grafana/helm-charts/issues/1385


prometheus: 
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ""
    additionalConfig:
      otlp:
        promoteResourceAttributes:
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.availability_zone
          - cloud.region
          - container.name
          - deployment.environment.name
          - k8s.cluster.name
          - k8s.container.name
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.replicaset.name
          - k8s.statefulset.name
        translationStrategy: NoUTF8EscapingWithSuffixes
    enableFeatures:
      - native-histograms
      - exemplar-storage
    enableRemoteWriteReceiver: true
    retention: 7d
    tsdb:
      outOfOrderTimeWindow: 15m
    storageSpec:
      volumeClaimTemplate:
       spec:
         storageClassName: oci-bv
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 50Gi

grafana:
  adminUser: admin
  adminPassword: prom-operator

  # This also publicly expose the /metrics endpoit
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - www.aimericsorin.me
    path: /
    tls:
      - secretName: monitoring-stack-cert-prod
        hosts:
        - www.aimericsorin.me

  persistence:
    enabled: true
    type: pvc
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  sidecar:
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: tempo
        traceIdLabelName: trace_id
        urlDisplayLabel: View traces

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      uid: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
        
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      uid: tempo
      url: http://tempo-query-frontend.monitoring:3100
      isDefault: false
      jsonData:
        httpMethod: POST
        serviceMap:
          datasourceUid: 'prometheus'
        nodeGraph:
            enabled: true
        streamingEnabled:
            search: false
            metrics: false
        tracesToMetrics:
            datasourceUid: 'prometheus'
            spanStartTimeShift: '1h'
            spanEndTimeShift: '-1h'
            tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
            queries:
              - name: 'Sample query'
                query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'