grafana:
  adminUser: admin
  adminPassword: admin

kubeControllerManager:
  endpoints:
    - 10.0.1.158
    - 10.0.1.143
    - 10.0.1.190

kubeEtcd:
  endpoints: 
    - 10.0.1.158
    - 10.0.1.143
    - 10.0.1.190

kubeScheduler:
  endpoints: 
    - 10.0.1.158
    - 10.0.1.143
    - 10.0.1.190

kubeProxy:
  endpoints: 
    - 10.0.1.158
    - 10.0.1.143
    - 10.0.1.190