# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
# data:
#   prometheus.yml: |
#     # Paste your Prometheus configuration here

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-config
# data:
#   custom-grafana.ini: |
#     # Custom Grafana configuration content here

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: k6
# spec:
#   selector:
#     matchLabels:
#       app: k6
#   template:
#     metadata:
#       labels:
#         app: k6
#     spec:
#       containers:
#       - name: k6
#         image: grafana/k6:0.46.0
#         env:
#         - name: K6_PROMETHEUS_RW_SERVER_URL
#           value: "http://prometheus:9090/api/v1/write"
#         - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
#           value: "true"
#       volumeMounts:
#       - name: k6-scripts
#         mountPath: /scripts
# volumes:
#   - name: k6-scripts
#     emptyDir: {}
