stream_over_http_enabled: true

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: tempo:4317

ingester:
  max_block_duration: 5m          

compactor:
  compaction:
    block_retention: 24h    
    compaction_window: 10m  

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: s3                     
    wal:
      path: /var/tempo/wal            
    s3:
      bucket: tempo           
      endpoint: minio:9000
      access_key: admin
      secret_key: password
      insecure: true

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] 
      generate_native_histograms: both