name: Deploy to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"

env:
  RUST_VERSION: 1.73

jobs:
  build-and-push-image:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    environment: development
    needs: [test, format, lint]

    env:
      HUB_NAME: "aimeric"
      IMAGE_NAME: "axum-demo"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push app docker image
        uses: docker/build-push-action@v4
        env:
          IMAGE_URL: ${{ vars.HUB_NAME }}/${{ vars.IMAGE_NAME }}
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.IMAGE_URL }}:latest
